### PR TITLE
Add support for torrent url and torrent file.

### PR DESCRIPTION
**Pull request by afedchin**
This is first of two PRs.
- changed processing of magnet link, now magnet link can be link to torrent file.
- added new parameter 'file' for support local torrent file path.

@steeve, please check first and foremost syntax.

### CODE REVIEW

**Comment by afedchin** [comment]
I've tested same logic into my .Net port of torrent2http. Its works as expected.

**Comment by steeve** [comment]
Ok, so `add_torrent_params.url` is really nice, and makes all our lives simpler.
I'm gonna change `--magnet` to `--uri` then. And use your findings :)

**Comment by steeve** [comment]
Do you think loading a local `.torrent` file is useful ? I'm using the raw uri/url and it works just fine, as per the libtorrent doc.

**Comment by afedchin** [comment]
I think local `.torrent` will be useful with a private trackers where `.torrent` can be downloaded after authorization only

**Comment by steeve** [comment]
Ah got it. Indeed.

**Comment by steeve** [comment]
Ok so I've added `file://` support for uris.
So the param is `--uri file://`, `--uri http://` or `--uri magnet:`

**Comment by afedchin** [comment]
Great! Thank you!

**Comment by Kaesian** [comment]
Hi guys,
Support for .local torrent files a great enhancement! However, it is not working for me. Torrent2http seems to crash.
Here are some details to narrow down the problem:
- I tried it both in Windows and in Linux (Xbian in Raspberry Pi). Windows notifies that torrent2http.exe stopped working, Xbian doesn't, but torrent never starts.
- The same .torrent works if using the http:// uri, so the problem is in file://
- I tried to place the .torrent inside the xbmctorrent's addon_data folder, in case it was not accessible outside, but it is not a solution.

Here is the xbmc.log, although the error seems to be in torrent2xbmc:
11:30:29 T:2893018176  NOTICE: screensaver Deactivated
11:30:31 T:2873095232  NOTICE: Thread Jobworker start, auto delete: true
11:30:31 T:2881483840  NOTICE: Thread Background Loader start, auto delete: false
11:30:35 T:2881483840  NOTICE: Previous line repeats 1 times.
11:30:35 T:2881483840  NOTICE: Thread XBPyThread start, auto delete: false
11:30:36 T:2881483840  NOTICE: -->Python Interpreter Initialized<--
11:30:37 T:2881483840 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
11:30:38 T:2881483840 WARNING: Previous line repeats 7 times.
11:30:38 T:2881483840  NOTICE: [xbmcswift2] Request for "/play/file%3A%2F%2F%2Fhome%2Fxbian%2F.xbmc%2Fuserdata%2Faddon_data%2Fplugin.video.xbmctorrent%2Ftv%2FmyLocalTorrent.torrent" matches rule for function "play"
11:30:38 T:2881483840 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
11:30:38 T:2881483840 WARNING: Previous line repeats 3 times.
11:30:38 T:2881483840  NOTICE: [plugin.video.xbmctorrent] Starting torrent2http...
11:30:38 T:2881483840  NOTICE: ['/home/xbian/.xbmc/addons/plugin.video.xbmctorrent/resources/bin/linux_arm/torrent2http', '--dlrate', '0', '--encryption', '1', '--dlpath', '/media/Elements/P2P/', '--uri', 'file:///home/xbian/.xbmc/userdata/addon_data/plugin.video.xbmctorrent/tv/myLocalTorrent.torrent', '--bind', ':37887']
11:30:44 T:2881483840  NOTICE: [plugin.video.xbmctorrent] Opening download dialog...
11:30:44 T:2881483840  NOTICE: [plugin.video.xbmctorrent] Waiting for file resolution...
11:32:12 T:3042828288   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.xbmctorrent/play/file%3A%2F%2F%2Fhome%2Fxbian%2F.xbmc%2Fuserdata%2Faddon_data%2Fplugin.video.xbmctorrent%2Ftv%2FmyLocalTorrent.torrent]
11:32:14 T:2881483840  NOTICE: Thread Background Loader start, auto delete: false
11:32:15 T:2873095232  NOTICE: Thread Jobworker start, auto delete: true

**Comment by francescosoft** [comment]
Hello guys,

I can't get it to work whith file:///, whith http:// everything works fine.
I tried also to transform the torrent file into a magnet link but the torrent never starts in this particular case. I've implemented another tracker there it works whith magnet transformation.
I realy need to get this working.
any advice ?

Thanks

**Comment by francescosoft** [comment]
Hey,

Is this project dead ?

Thanks

**Comment by steeve** [comment]
It's not, but I'm sidetracked on other projects for now

**Comment by francescosoft** [comment]
OK Steeve :)

No problem. Thanks for your answer ;)
If you get some time can you please check why file:// uris are not working .....
Thanks,

Francesco

**Comment by steeve** [comment]
The weird thing is that support is indeed there, didn't test it though (sorry):
https://github.com/steeve/torrent2http/blob/master/torrent2http.go#L357

**Comment by francescosoft** [comment]
I think it is a bug soemwhere because it dosen't work. I tested whith xbmc and also in the terminal and i does not work. I can't get a file listing and status tells me that everything is on 0. The same file over http works well.

Thanks,

Franz

**Pull request closed without merging**
